routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('companies', 'CompanyController');
Route::resource('stations', 'StationController');

Route::get('/nearest-stations','HomeController@index')->name('nearest.index');
Route::post('/nearest-stations','HomeController@getStations');

app/Company.php
<?php
namespace App;

use Franzose\ClosureTable\Models\Entity;

class company extends Entity implements companyInterface
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'companies';

    /**
     * ClosureTable model instance.
     *
     * @var companyClosure
     */
    protected $closure = 'App\companyClosure';

    protected $fillable=['name','company_id'];

    public function stations()
    {
        return $this->hasMany('App\Station');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use App\Events\CompanyDeleted;
use App\Station;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies=Company::paginate(10);

        return view('company.index',compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies=Company::all();
        return view('company.create',compact('companies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required',
        ]);

        $company=new Company();
        $company->name=$request->name;

        if($request->has('parent_company'))
        {
           $parent=Company::find($request->parent_company);
           $parent->addChild($company);
        }
        else{
            $company->save();
        }

        return redirect('companies');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        $child_companies=$company->getChildren();
        $descendant_companies_id=$company->getDescendants(['id'])->pluck('id')->toArray();
        $companies_id=array_merge($descendant_companies_id,[$company->id]);

        $descendant_stations=DB::table('stations')
            ->whereIn('company_id', $companies_id)
            ->get();

        return view('company.show',compact('company','child_companies','descendant_stations'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('company.edit',compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Company $company)
    {
        $validatedData = $request->validate([
            'name' => 'required',
        ]);
        $company->name=$request->name;
        $company->save();

        return redirect( route('companies.show',['id'=>$company->id]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        $company_id = $company->id;
        $parent = $company->getParent();
        $station_count = $company->station_count;
        $company->forceDelete();
        Station::where("company_id", $company_id)->delete();
        event(new CompanyDeleted($parent,$station_count));

        return redirect('/companies');
    }
}

resources/views/company/create.blade.php
@extends('layouts.master',['title'=>'Create Company'])

@section('main-container')
    @if ($errors->any())
        <div class="alert alert-danger mt-3">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <div class="card mt-5">


        <div class="card-header">
            <h2 class="card-header-title">
                Create a Company
            </h2>
        </div>
        <div class="card-body">
            <form class="" method="POST" action="/companies">
                {{ csrf_field() }}

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="name">Name</label>
                    </div>
                    <input class="form-control" name="name" type="text">
                </div>

                @if(count($companies))
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="parent_company">Parent Company</label>
                    </div>
                    <select class="custom-select" name="parent_company">
                        <option selected>Select parent Company</option>
                        @foreach($companies as $company)
                            <option value="{{$company->id}}">{{$company->name}}</option>
                        @endforeach
                    </select>
                </div>

                @endif
                <button class="btn btn-primary btn-block" type="submit" dusk="submit">Add</button>

            </form>


        </div>


    </div>



@endsection

resources/views/company/edit.blade.php
@extends('layouts.master',['title'=>'Edit '.$company->name || 'Edit Company Details'])

@section('main-container')
    @if ($errors->any())
        <div class="alert alert-danger mt-3">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <div class="card mt-5">


        <div class="card-header">
            <h2 class="card-header-title">
                Update Company
            </h2>
        </div>
        <div class="card-body">
            <form class="" method="POST" action="/companies/{{$company->id}}">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="PUT">

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="name">Name</label>
                    </div>
                    <input class="form-control" name="name" type="text" value="{{$company->name}}">
                </div>

                <button class="btn btn-primary btn-block" type="submit">Update</button>

            </form>


        </div>


    </div>



@endsection

resources/views/company/index.blade.php
@extends('layouts.master',['title'=>'View all Companies'])

@section('main-container')


    <div>

        @if (count($companies)> 0)
        <ul class="list-group">

           @foreach($companies as $company)

                <a href="{{route('companies.show',['id'=>$company->id])}}">
                    <li class="card my-2">

                        <div class="card-body">
                            <h4>{{$company->name}}</h4>
                            <p>
                                @if(isset($company->parent))
                                    Parent Company : {{$company->getParent()->name}} |
                                @endif
                                @if(isset($company->station_count))
                                    Stations : {{$company->station_count}}
                                @endif
                            </p>
                        </div>

                    </li>
                </a>

               @endforeach

        </ul>

            {{ $companies->links() }}

        @else
            <div class="alert alert-info mt-5">
                <h5>There are no companies currently</h5>
            </div>
        @endif



    </div>





@endsection

resources/views/company/show.blade.php
@extends('layouts.master',['title'=>'View Company Details'])

@section('main-container')

    <div class="row">
        <div class="col-md-8">
            <div>

                @if ($errors->any())
                    <div class="alert alert-danger mt-3">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                @if (count($company) > 0)
                    <div class="card my-2">
                        <div class="card-header d-inline-flex">
                            <h4 class="w-50 pull-left">{{$company->name}}</h4>
                            <div class="w-50 d-inline-flex">
                                <a class="w-25 btn btn-info pull-right" href="{{route('companies.edit',['id'=>$company->id])}}">Edit</a>

                                <form class="w-75 px-2" action="{{route('companies.destroy',['id'=>$company->id])}}" method="POST">
                                    {{csrf_field()}}
                                    <input type="hidden" name="_method" value="DELETE">
                                    <button class=" btn btn-danger pull-right" type="submit">Delete</button>

                                </form>

                            </div>
                        </div>
                        @if($company->getParent()!=null||($company->hasChildren()))
                            <div class="card-body">
                                @if(count($company->getParent()) > 0)
                                    <div class="card">
                                       <div class="card-header">
                                           <h5 class="">
                                               Parent Company
                                           </h5>
                                           <a href="{{route('companies.show',['id'=>$company->getParent()->id])}}"> {{$company->getParent()->name}}</a>
                                       </div>
                                    </div>
                                @endif

                                @if(count($child_companies)>0)
                                    <div class="card mt-2">
                                        <h5 class="card-header">

                                            Child Companies

                                        </h5>
                                        <div class="card-body">
                                            <ul class="list-group list-group-flush">
                                                @foreach($child_companies as $child_company)
                                                    <li class="list-group-item">
                                                        <a href="{{route('companies.show',['id'=>$child_company->id])}}"> {{$child_company->name}}</a>
                                                    </li>
                                                @endforeach

                                            </ul>
                                        </div>
                                    </div>
                                @endif
                            </div>

                        @endif

                    </div>
                @else
                    <div class="alert alert-info mt-5">
                        <h5>There are no companies currently</h5>
                    </div>
                @endif



            </div>
        </div>
        <div class="col-md-4">
           <div class="card my-2">
               <div class="card-header">
                   <h4>All Child Stations</h4>
               </div>
               <div class="card-body">
                   @if (count($descendant_stations)>0)
                       <ul class="list-group list-group-flush">

                              @foreach($descendant_stations as $station)
                                   <li class="list-group-item">
                                       <a href="{{route('stations.show',['id'=>$station->id])}}">
                                           {{$station->name}}
                                       </a>
                                   </li>
                               @endforeach


                       </ul>
                   @else
                       <div class="alert alert-info mt-5">
                           <h5>There are no stations currently</h5>
                       </div>
                   @endif
               </div>
           </div>
        </div>
    </div>






@endsection