routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('companies', 'CompanyController');
Route::resource('stations', 'StationController');

Route::get('/nearest-stations','HomeController@index')->name('nearest.index');
Route::post('/nearest-stations','HomeController@getStations');

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{{$title}}</title>

    <style>
        .list-group a{

            text-decoration: none;
            color:#212121;
        }
        .list-group li:hover{
            background: #f5f5f5!important;
            border:1px solid #ffffff;
        }
    </style>
</head>
<body class="bg-light">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Develon Charging</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('nearest.index')}}">Find Nearest Station</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('companies.index')}}">View all Companies</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="{{route('companies.create')}}">Add Company</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="{{route('stations.index')}}">View Stations</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="{{route('stations.create')}}">Add Station</a>
            </li>
        </ul>
    </div>
</nav>
<div class="container ">
    @yield('main-container')
</div>

</body>
</html>