routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('companies', 'CompanyController');
Route::resource('stations', 'StationController');

Route::get('/nearest-stations','HomeController@index')->name('nearest.index');
Route::post('/nearest-stations','HomeController@getStations');

app/Station.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Station extends Model
{

    protected $fillable=['name','latitude','longitude'];

    public function company()
    {
        return $this->belongsTo('App\Company');
    }
}

app/Http/Controllers/StationController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use App\Events\StationAdded;
use App\Events\StationRemoved;
use App\Jobs\DecrementStationCount;
use App\Jobs\IncrementStationCount;
use App\Station;
use Illuminate\Http\Request;

class StationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $stations=Station::all();
        $company=Company::first();
        return view('station.index',compact('stations','company'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies=Company::all();
        return view('station.create',compact('companies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required',
            'latitude'=>'required',
            'longitude'=>'required',
            'parent_company'=>'required|integer'
        ]);

        $company=Company::find($request->parent_company);

        $station=new Station();
        $station->name=$request->name;
        $station->longitude=$request->longitude;
        $station->latitude=$request->latitude;

        $company->stations()->save($station);

        event(new StationAdded($station));

        return redirect('/stations');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Station  $station
     * @return \Illuminate\Http\Response
     */
    public function show(Station $station)
    {
        return view('station.show',compact('station'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Station  $station
     * @return \Illuminate\Http\Response
     */
    public function edit(Station $station)
    {
        $companies=Company::all();
        return view('station.edit',compact('station','companies'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Station  $station
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Station $station)
    {
        $validatedData = $request->validate([
            'name' => 'required',
            'latitude'=>'required',
            'longitude'=>'required',
            'parent_company'=>'required|integer'
        ]);
        $company=Company::find($request->parent_company)->first();

        $station=new Station();
        $station->name=$request->name;
        $station->longitude=$request->longitude;
        $station->latitude=$request->latitude;

        $company->stations()->save($station);

        return redirect( route('companies.show',['id'=>$station->id]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Station  $station
     * @return \Illuminate\Http\Response
     */
    public function destroy(Station $station)
    {
        $station->forceDelete();
        event(new StationRemoved($station));
        return redirect(route('stations.index'));
    }
}

resources/views/station/create.blade.php
@extends('layouts.master',['title'=>'Create station'])

@section('main-container')
    @if ($errors->any())
        <div class="alert alert-danger mt-3">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <div class="card mt-5">
        <div class="card-header">
            <h2 class="card-header-title">
                Create a Station
            </h2>
        </div>
        <div class="card-body">
            <form class="" method="POST" action="/stations">
                {{ csrf_field() }}

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="name">Name</label>
                    </div>
                    <input class="form-control" name="name" type="text" required value="{{old('name')}}">
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="latitude">Latitude</label>
                    </div>
                    <input class="form-control" name="latitude" type="text" required value="{{old('latitude')}}">
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="longitude">Longitude</label>
                    </div>
                    <input class="form-control" name="longitude" type="text" required value="{{old('longitude')}}">
                </div>

                @if(count($companies)>0)
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <label class="input-group-text" for="parent_company">Parent Company</label>
                        </div>
                        <select class="custom-select" name="parent_company" required>
                            <option>Select parent Company</option>
                            @foreach($companies as $company)
                                <option value="{{$company->id}}">{{$company->name}}</option>
                            @endforeach
                        </select>
                    </div>

                @endif
                <button class="btn btn-primary btn-block" type="submit">Add</button>

            </form>


        </div>


    </div>



@endsection

resources/views/station/edit.blade.php
@extends('layouts.master',['title'=>'Edit station'])

@section('main-container')
    @if ($errors->any())
        <div class="alert alert-danger mt-3">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <div class="card mt-5">


        <div class="card-header">
            <h2 class="card-header-title">
                Update Station
            </h2>
        </div>
        <div class="card-body">
            <form class="" method="POST" action="/stations/{{$station->id}}">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="PUT">

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="name">Name</label>
                    </div>
                    <input class="form-control" name="name" type="text" required value="{{$station->name}}">
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="latitude">Latitude</label>
                    </div>
                    <input class="form-control" name="latitude" type="text" required value="{{$station->latitude}}">
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="longitude">Longitude</label>
                    </div>
                    <input class="form-control" name="longitude" type="text" required value="{{$station->longitude}}">
                </div>

                @if(count($companies)>0)
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <label class="input-group-text" for="parent_company">Parent Company</label>
                        </div>
                        <select class="custom-select" name="parent_company" required>
                            <option>Select parent Company</option>
                            @foreach($companies as $company)
                                {{--<option value="{{$company->id}}" @if($station->company->id===$company->id) selected @endif>{{$company->name}}</option>--}}
                            @endforeach
                        </select>
                    </div>
                @endif
                <button class="btn btn-primary btn-block" type="submit">Add</button>

            </form>


        </div>


    </div>



@endsection

resources/views/station/index.blade.php
@extends('layouts.master',['title'=>'View Stations'])

@section('main-container')
    <div>
        @if (count($stations)> 0)
        <ul class="list-group">

           @foreach($stations as $station)


                    <li class="card my-2">
                        <div class="card-body">
                            <a href="{{route('stations.show',['id'=>$station->id])}}">

                                    <h4>{{$station->name}}</h4>
                                    <p>Latitude: {{$station->latitude}} | Longitude: {{$station->longitude}}
                                    @if(isset($station->company))
                                      | Parent Company : {{$station->company->name}}
                                    @endif
                                    </p>

                            </a>
                            <form class="" action="{{route('stations.destroy',['id'=>$station->id])}}" method="POST">
                                {{csrf_field()}}
                                <input type="hidden" name="_method" value="DELETE">
                                <button class=" btn btn-danger pull-right" type="submit">Delete</button>

                            </form>
                        </div>
                    </li>


               @endforeach

        </ul>
        @else
            <div class="alert alert-info mt-5">
                <h5>There are no stations currently</h5>
            </div>
        @endif



    </div>





@endsection

resources/views/station/show.blade.php
@extends('layouts.master',['title'=>'View station'])

@section('main-container')
    <div>
        @if (count($station) > 0)
                    <div class="card my-2">
                        <div class="card-header d-inline-flex">
                            <h4 class="w-50 pull-left">{{$station->name}}</h4>
                            <div class="w-50 d-inline-flex">
                                <a class="w-25 btn btn-info pull-right" href="{{route('stations.edit',['id'=>$station->id])}}">Edit</a>
                                <form class="w-75 px-2" action="{{route('stations.destroy',['id'=>$station->id])}}" method="POST">
                                    {{csrf_field()}}
                                    <input type="hidden" name="_method" value="DELETE">
                                    <button class=" btn btn-danger pull-right" type="submit">Delete</button>

                                </form>

                            </div>
                        </div>
                        <div class="card-body">
                            @if(isset($station))
                                <ul class="list-group">

                                    <li class="list-group-item">
                                        <p>Latitude : {{$station->latitude}}</p>
                                    </li>
                                    <li class="list-group-item">
                                        <p>Longitude : {{$station->longitude}}</p>
                                    </li>


                                </ul>
                            @endif

                            @if(isset($station->company))
                                <div class="card mt-2">
                                    <h5 class="card-header">
                                        Parent Company
                                    </h5>
                                    <div class="card-body">
                                        <a href="{{route('companies.show',['id'=>$station->company->id])}}"> {{$station->company->name}}</a>
                                    </div>
                                </div>
                            @endif


                        </div>

                    </div>
       @else
            <div class="alert alert-info mt-5">
                <h5>There are no stations currently</h5>
            </div>
        @endif



    </div>





@endsection